#.SUFFIXES:
#.SUFFIXES: .g .o

LIBS=gao.o

all: $(LIBS)

### this not works.
%.o:%c
	@echo "in %.o:%c"

### this works both.
#%.o:%.c    
#	@echo "in %.o:%.c"

### this works both.
#.c.o:    
#	@echo "in .c.o"
