.PHONY:${all}
all: HASHMAP MAP UNORDERMAP SIMPLE

HASHMAP:
	g++ hash_map.cc -o hash_map

MAP:
	g++ map.cc -o map

UNORDERMAP:
	g++ unordered_map.cc -o unordered_map

SIMPLE:
	g++ simple_type_hash.cc -o simple


clean:
	rm -rf hash_map map unordered_map simple a.out *.o tags 
