all:
	@echo "+++++++++++++++++++++++++++++"
	@echo "layer2 all"
	@echo "+++++++++++++++++++++++++++++"
	gcc -M layer2.c 
	gcc -MM layer2.c 
	gcc -M layer2.c -o layer2

install:
	@echo "+++++++++++++++++++++++++++++"
	@echo "layer2 install"
	@echo "+++++++++++++++++++++++++++++"
	gcc -M layer2.c 
	gcc -MM layer2.c 
	gcc -M layer2.c -o layer2
	
